-- SQL Script to set up the schema for Battle Quotes
-- Run this script in the Supabase SQL Editor (https://supabase.com)

-- 1. Create the user_quotes table
CREATE TABLE IF NOT EXISTS public.user_quotes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    quote TEXT NOT NULL
);

-- 2. Create the votes table
CREATE TABLE IF NOT EXISTS public.votes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    quote_id TEXT NOT NULL
);

-- 3. Create the active_combat table to sync active quotes in real-time
CREATE TABLE IF NOT EXISTS public.active_combat (
    slot TEXT PRIMARY KEY, -- 'q1' or 'q2'
    text TEXT NOT NULL,
    author TEXT DEFAULT 'ANONYME' NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Enable Row Level Security (RLS)
ALTER TABLE public.user_quotes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.votes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.active_combat ENABLE ROW LEVEL SECURITY;

-- 5. Create RLS Policies for user_quotes
-- Allow anyone (including anonymous users) to insert new quotes
CREATE POLICY "Allow anonymous and authenticated insert to user_quotes" 
ON public.user_quotes 
FOR INSERT 
TO public 
WITH CHECK (true);

-- Allow anyone to read submitted quotes (required for fetching submissions in admin panel)
CREATE POLICY "Allow public read access to user_quotes" 
ON public.user_quotes 
FOR SELECT 
TO public 
USING (true);

-- 6. Create RLS Policies for votes
-- Allow anyone (including anonymous users) to cast a vote
CREATE POLICY "Allow anonymous and authenticated insert to votes" 
ON public.votes 
FOR INSERT 
TO public 
WITH CHECK (true);

-- Allow anyone to view votes (for count/percentage displays)
CREATE POLICY "Allow public read access to votes" 
ON public.votes 
FOR SELECT 
TO public 
USING (true);

-- Allow authenticated users (Admins) to delete/reset votes
CREATE POLICY "Allow authenticated users to delete votes" 
ON public.votes 
FOR DELETE 
TO authenticated 
USING (true);

-- 7. Create RLS Policies for active_combat
-- Allow anyone (public/anonymous) to read the active quotes
CREATE POLICY "Allow public read access to active_combat" 
ON public.active_combat 
FOR SELECT 
TO public 
USING (true);

-- Allow only authenticated users (Admins) to modify the active quotes
CREATE POLICY "Allow authenticated users to modify active_combat" 
ON public.active_combat 
FOR ALL 
TO authenticated 
USING (true)
WITH CHECK (true);

-- 8. Enable Realtime Replication for active_combat and votes tables
-- This allows connected clients to see quote swaps and live vote count updates instantly!
DO $$
BEGIN
  ALTER PUBLICATION supabase_realtime DROP TABLE active_combat, votes;
EXCEPTION WHEN OTHERS THEN
  -- ignore error if tables were not already in the publication
END $$;

ALTER PUBLICATION supabase_realtime ADD TABLE active_combat;
ALTER PUBLICATION supabase_realtime ADD TABLE votes;

-- 9. Force Supabase API (PostgREST) to reload its schema cache immediately
-- This resolves the "Could not find table in the schema cache" error instantly!
NOTIFY pgrst, 'reload schema';
